server:
  port: 8181
#debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot2test?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false

#  spring.jackson.date-formate = yyyy-MM-dd HH:mm:ss
#  spring.jackson.time-zone = GMT+8



